---
config:
  theme: redux
---
flowchart TD
    A(["Start"]) --> B{"Decision"}
    B --> C["Option A"]
    n1["Sample Label"] --> n2["Untitled Node"] & n3["Untitled Node"] & n4["Untitled Node"] & n5["Untitled Node"]
    n1@{ icon: "fa:object-ungroup", pos: "b", h: 200}
    style A fill:#2962FF
    style n1 stroke:#FFF9C4
    linkStyle 0 stroke:#616161,fill:none
